// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzdgionesavhpcodanex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZGdpb25lc2F2aHBjb2RhbmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDk4MTgsImV4cCI6MjA1ODU4NTgxOH0.Oy8gwPgK2qfycKhz0d7mbEm-MBewQCvb9aLvgv9nqVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);